import { Geist, Geist_Mono, Indie_Flower,Caveat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SplashCursor from "@/components/SplashCursor";
import localFont from "next/font/local";


const minecraftFont = localFont({
  src: './fonts/minecraft_font.ttf',
  display: 'swap',
  variable: '--font-minecraft',
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const indieFlower = Indie_Flower({
  variable: "--font-indie-flower",
  subsets: ["latin"], 
  weight: "400",
});
const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${minecraftFont.variable} ${caveat.variable} ${indieFlower.variable} antialiased`}
      >
        <Navbar/>
        <SplashCursor />
        {children}
      </body>
    </html>
  );
}
